on:
    release:
      types: [created]

env:
    CARGO_TERM_COLOR: always

jobs:
    docker:
      name: Publish to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: zhaozisong0/rwrs-server:latest, zhaozisong0/rwrs-server:${{ github.ref_name }}
            build-args: |
              "TAG_NAME=${{ github.ref_name }}"
